### PR TITLE
Add blog post on DeCodeCafe podcast

### PR DESCRIPTION
**Pull request by wyphan**
@rahulkhinchi03 and @Vyom-Yadav, please take a look and check the links. Please feel free to make any changes to it as soon as you accept the invitation to collaborate :grin: 

My website is based on the default GitHub Pages template, which I have modified little by little to suit my needs over time. It uses Jekyll and Kramdown to render the original Markdown source into a proper HTML page. For instance, the original template doesn't allow for more than one author, which I added in f0ab5c2.

To test locally, simply clone the repo and follow the instructions I put in the README.md file. Please don't hesitate to ask me anything to make this blog post happen!

### CODE REVIEW

**Review by Rahulkhinchi03 — COMMENTED** [review]
"Grammetical Errors"

**Comment by wyphan** [comment]
Thanks for the feedback! I've just pushed a commit to fix the Markdown formatting for links in the first paragraph.
I use this Markdown cheatsheet btw: https://commonmark.org/help/
And I use the ReText editor, which has a built-in preview: https://github.com/retext-project/retext

**Comment by Rahulkhinchi03** [comment]
It is ready to merge now.

**Comment by wyphan** [comment]
Let's wait for @Vyom-Yadav 's feedback before merging it.

**Comment by Vyom-Yadav** [comment]
Sure, I will review it in few hours, going to the gym rn 😄

**Review by Rahulkhinchi03 — APPROVED** [review]

**Review by Vyom-Yadav — APPROVED** [review]
Everything looks good 😄

**Pull request merged**
